### ISSUE TITLE
Where're sample csv files?

### ISSUE THREAD

**Issue by kekyo** [enpedasi/elixir_agg_csv#2]
Your slide https://www.slideshare.net/YoshiiroUeno/elixir-go-c-scalanodejs is nice!
I'm wanna test my envs. Where're sample csv files?

**Comment by enpedasi** [comment]
Thak you! 
Csv FIle is here.
https://github.com/enpedasi/fukuokaex5_csv

**Comment by kekyo** [comment]
I wrote PLINQ version C# sample code at my gist.
https://gist.github.com/kekyo/11b5da1548f82658dbdf63a0678a895b

I will send you PR if necessary :)
